{% set import_path = "github.com/mozilla/sops" %}
{% set version = "3.6.1" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/'+import_path).replace("/", os.sep) %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ import_path }}/archive/v{{ version }}.tar.gz
    sha256: bb6611eb70580ff74a258aa8b9713fdcb9a28de5a20ee716fe6b516608a60237

build:
  number: 0
  skip: true  # [win]
  script:
    - pushd {{ pkg_src }}
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - make  # [unix]

test:
  commands:
    - which sops    # [not win]
    - where sops    # [win]
    - sops --help

about:
  home: https://github.com/mozilla/sops
  license: MPL-2.0
  license_family: MOZILLA
  license_file: {{ pkg_src }}/LICENSE
  summary: Simple and flexible tool for managing secrets
  description: |
    sops is an editor of encrypted files that supports YAML, JSON, ENV, INI
    and BINARY formats and encrypts with AWS KMS, GCP KMS, Azure Key Vault
    and PGP.

extra:
  recipe-maintainers:
    - xhochy
