{% set name = "sops" %}
{% set version = "3.9.4" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    url: https://github.com/getsops/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3e0fc9a43885e849eba3b099d3440c3147ad0a0cd5dd77a9ef87c266a8488249

build:
  number: 0
  script:
    - cd src
    - go mod tidy
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/sops ./cmd/sops   # [not win]
    - go build -v -o %LIBRARY_BIN%\sops.exe .\cmd\sops   # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }} >=1.22.7
    - go-licenses

test:
  commands:
    - which sops    # [not win]
    - where sops    # [win]
    - sops --help

about:
  home: https://github.com/getsops/sops/
  license: MPL-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: sops manages JSON, YAML and BINARY documents to be encrypted or decrypted.
  description: |
    SOPS is an editor of encrypted files that supports YAML, JSON, ENV, INI and BINARY formats and encrypts with AWS KMS, GCP KMS, Azure Key Vault, age, and PGP.

extra:
  recipe-maintainers:
    - xhochy
    - fhoehle
