{% set import_path = "github.com/getsops/sops" %}
{% set version = "3.9.1" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/'+import_path).replace("/", os.sep) %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ import_path }}/archive/v{{ version }}.tar.gz
  sha256: d79e8caaef3134d00f759231e8ef587b791996e2e45319ffe83dee1ab01aebda

build:
  number: 0
  script:
    - go build -v -o $PREFIX/bin/sops github.com/getsops/sops/v3/cmd/sops   # [not win]
    - go build -v -o %LIBRARY_PREFIX%/bin/sops.exe github.com/getsops/sops/v3/cmd/sops   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go') }} >=1.13      # [linux] # seg faults occure for cgo
    - {{ compiler('go-cgo') }} >=1.13  # [not linux]
    - make

test:
  commands:
    - which sops    # [not win]
    - where sops    # [win]
    - sops --help

about:
  home: https://github.com/mozilla/sops
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Simple and flexible tool for managing secrets
  description: |
    sops is an editor of encrypted files that supports YAML, JSON, ENV, INI
    and BINARY formats and encrypts with AWS KMS, GCP KMS, Azure Key Vault
    and PGP.

extra:
  recipe-maintainers:
    - xhochy
    - fhoehle
